//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat_Items
    {
        public int Id { get; set; }
        public int NUM_ITEM { get; set; }
        public string ALIAS_JOUEUR { get; set; }
    }
}
