//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHAT_POKEMON
    {
        public int Id { get; set; }
        public int NUM_POKEMON { get; set; }
        public string ALIAS_JOUEUR { get; set; }
        public int LVL { get; set; }
        public int ATTAQUE1 { get; set; }
        public Nullable<int> ATTAQUE2 { get; set; }
        public Nullable<int> ATTAQUE3 { get; set; }
        public Nullable<int> ATTAQUE4 { get; set; }
    }
}
