//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        public string ALIAS { get; set; }
        public string MOT_PASSE { get; set; }
        public string DIVISION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> NOMBRE_VICTOIRE { get; set; }
        public Nullable<int> NOMBRE_PARTIES_JOUES { get; set; }
        public Nullable<int> EXPERIENCE { get; set; }
    }
}
