//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainBDEntities : DbContext
    {
        public MainBDEntities()
            : base("name=MainBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achat_Items> Achat_Items { get; set; }
        public DbSet<ACHAT_POKEMON> ACHAT_POKEMON { get; set; }
        public DbSet<Attaque> Attaques { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Joueur> Joueurs { get; set; }
        public DbSet<Pokemon> Pokemons { get; set; }
    }
}
