//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string NOM_POKEMON { get; set; }
        public string PHOTO { get; set; }
        public string TYPE { get; set; }
        public int PRIX { get; set; }
        public int VIE { get; set; }
        public int ATTAQUE { get; set; }
        public int DEFENSE { get; set; }
        public Nullable<int> VITESSE { get; set; }
        public Nullable<int> ATTAQUE_DEFAUT { get; set; }

        public static Pokemon Afficher(int num)
        {
            MainBDEntities Donnees = new MainBDEntities();
            Pokemon result = Donnees.Pokemons.Find(num);

            return result;
        }
    }
}
